baseURL: "https://hugo-profile.netlify.app"
languageCode: "en-us"
title: "Wahyu Blog"
theme: "./.."
relativeURLs: true

googleanalytics: UA-167646412-8
disqusShortname:
Paginate: 3
markup:
  goldmark:
    renderer:
      unsafe: true

taxonomies:
  tag: "tags"
  category: "categories"

enableEmoji: true
params:
  version: 3

  favicon: "/images/fav.png"
  description: "A high performance hugo theme for personal portfolio and blog."

  # Navbar Menus
  customMenus:
    - name: "Blog"
      Url: "/blog"

  # home
  disable_home: false
  profile_image: "/images/foto.jpeg"
  name: "Mochamad Wahyu"
  namecolor: ffc107
  profession: "Student of SMK Negeri Pasirian"
  github: "https://github.com/WahyuQwe12/"
  twitter: "https://twitter.com/Wahyuu_141?t=YRDw2f2gWqR1zgJXB0Ttkw&s=08"
  instagram: "https://instagram.com/whyuuu_14/"
  facebook: "https://facebook.com/mochamad.wahyu.108/"

  # About
  disable_about: false
  descripe_l1_person: "Selamat datang di blog saya. Disini saya akan membagikan artikel artikel mengenai teknologi mungkin akan bermanfaat untuk kita semua. Terima kasih"
  descripe_l2_person: "Disini saya akan membagikan beberapa hasil pencarian tentang teknologi. [here](#projects)"
  skills:
    - name: Game
      percentage: 90
    - name: Desain
      percentage: 80
    - name: Hiking
      percentage: 90
    - name: Mencintaimu
      percentage: 100

  # Experience
  disable_experience: false
  Experience:
    - company: "Google"
      # id: "google-user"   // use this, when you want to change the id(used for navigation)
      role: "Software User"
      startdate: 2016
      enddate: Until Now
      featuredpoints:
        - point: Mencari sumber informasi penting.
        - point: Sebagai media untuk pembelajaran.
    - company: "Facebook"
      # id: "facebook-user" // use this, when you want to change the id(used for navigation)
      role: "User"
      startdate: 2017
      enddate: Until Now
      featuredpoints:
        - point: Digunakan untuk berkomunikasi dengan orang orang.
        - point: Digunakan untuk berkomunikasi dengan orang orang
    - company: "Instagram"
      # id: "instagram-user" // use this, when you want to change the id(used for navigation)
      role: "User"
      startdate: 2018
      enddate: Until Now
      featuredpoints:
        - point: Untuk mencari hiburan saja.
        - point: Sarana berkomunikasi dengan orang lain.

  # Education
  disable_education: false
  education:
    - degree: "First"
      branch: "School"
      university: "SDN Sumberurip 02"
      startedyear: "2010"
      graduation: "2016"
    - degree: "Islamic Junior High"
      branch: "School"
      university: "SMP Islam Pronojiwo"
      startedyear: "2016"
      graduation: "2019"
    - degree: "Vocational"
      branch: "School"
      university: "SMK Negeri Pasirian"
      startedyear: "2019"
      graduation: "2022"

  # Projects
  disable_projects: false
  projects:
    - name: "Example project without details"
      img: /images/project.jpg
      githublink: "https://github.com/"
      featuredlink: "/"
      description: "Description of project"

  # Achievements
  disable_achievements: false
  achievements:
    - title: Classmate Football
      description:  Ketika perlombaan classmate kita meraih juara 3 putra dan juara 4 putri
      img: /images/arcv1.jpeg
    - title: Competition winner
      description: We are developed a product which can help others.
      img: /images/achiv.jpg
    - title: Competition winner
      description: We are developed a product which can help others.
      img: /images/achiv.jpg
    - title: Competition winner
      description: We are developed a product which can help others.
      img: /images/achiv.jpg

  # Contact
  disable_contact: false
  contact_content: Email saya selalu aktif 24 jam. kirimkan saja pertanyaan mu. akan saya balas secepatnya. Terima kasih telah mengunjungi web saya.
  email: "wahyuex4@gmail.com"

  # Footer
  socialiconfooter: true
  recentposts: true

  # Blog
  showdescription: false
  tweet: true
